#!/usr/bin/env bash
set -e

cd "$(git rev-parse --show-toplevel)"

exec direnv exec . bash -c '
  set -e
  go test ./...
  go build -o specdown ./cmd/specdown/
  go build -o specdown-adapter-shell ./cmd/specdown-adapter-shell/
  export PATH="$(pwd):$PATH"
  ./specdown run -config selfspec.json
'
