#!/usr/bin/env bash
set -e

cd "$(git rev-parse --show-toplevel)"

exec direnv exec . bash -c '
  set -e
  golangci-lint run
  go test ./...
  mkdir -p bin
  go build -o bin/specdown ./cmd/specdown/
  go build -o bin/specdown-adapter-shell ./cmd/specdown-adapter-shell/
  export PATH="$(pwd)/bin:$PATH"
  bin/specdown run -config selfspec.json
  bin/specdown run -config specdown.json
'
