#!/usr/bin/env bash
set -e

cd "$(git rev-parse --show-toplevel)"

cleanup() { rm -rf .tmp-bin; }
trap cleanup EXIT

echo "Running tests..."
go test ./...

echo "Running lint..."
golangci-lint run ./...

echo "Building specdown..."
go generate ./cmd/specdown/...
mkdir -p .tmp-bin
go build -o .tmp-bin/specdown ./cmd/specdown
go build -o .tmp-bin/specdown-adapter-shell ./cmd/specdown-adapter-shell
export PATH="$PWD/.tmp-bin:$PATH"

echo "Running selfspecs..."
specdown run

echo "Running example specs..."
cd examples/pocket-board && ../../.tmp-bin/specdown run
