version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gocognit
    - bodyclose
    - nilerr
    - errorlint
    - unparam
    - unconvert

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
    gocognit:
      min-complexity: 15
